package dev.toliner.openrouter.l1.responses

import dev.toliner.openrouter.ExperimentalOpenRouterApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response object returned by the OpenRouter Responses API.
 *
 * This is an experimental API that mirrors OpenAI's responses endpoint structure.
 *
 * **Note:** This API is experimental and subject to change. It is marked with [ExperimentalOpenRouterApi].
 *
 * @property id Unique identifier for this response
 * @property objectType Object type identifier (e.g., "response")
 * @property created Unix timestamp (seconds) when this response was created
 * @property model Model identifier used to generate this response
 * @property choices List of response choices generated by the model
 *
 * @see ResponseChoice
 * @see CreateResponseRequest
 */
@ExperimentalOpenRouterApi
@Serializable
public data class ResponseObject(
    @SerialName("id")
    val id: String,
    @SerialName("object")
    val objectType: String,
    @SerialName("created")
    val created: Long,
    @SerialName("model")
    val model: String,
    @SerialName("choices")
    val choices: List<ResponseChoice>
)

/**
 * A single response choice from the model.
 *
 * **Note:** This API is experimental and subject to change. It is marked with [ExperimentalOpenRouterApi].
 *
 * @property index Index of this choice in the list of choices
 * @property message The generated message content
 * @property finishReason Reason why the model stopped generating (e.g., "stop", "length", "tool_calls")
 *
 * @see ResponseObject
 * @see ResponseMessage
 */
@ExperimentalOpenRouterApi
@Serializable
public data class ResponseChoice(
    @SerialName("index")
    val index: Int,
    @SerialName("message")
    val message: ResponseMessage,
    @SerialName("finish_reason")
    val finishReason: String
)

/**
 * Message content within a response choice.
 *
 * **Note:** This API is experimental and subject to change. It is marked with [ExperimentalOpenRouterApi].
 *
 * @property role Role of the message sender (typically "assistant")
 * @property content Text content of the message; null if the message contains only tool calls
 * @property toolCalls Optional list of tool calls made by the model
 *
 * @see ResponseChoice
 * @see ResponseToolCall
 */
@ExperimentalOpenRouterApi
@Serializable
public data class ResponseMessage(
    @SerialName("role")
    val role: String,
    @SerialName("content")
    val content: String?,
    @SerialName("tool_calls")
    val toolCalls: List<ResponseToolCall>? = null
)

/**
 * A tool (function) call made by the model.
 *
 * **Note:** This API is experimental and subject to change. It is marked with [ExperimentalOpenRouterApi].
 *
 * @property id Unique identifier for this tool call
 * @property type Type of tool call (typically "function")
 * @property function Function call details including name and arguments
 *
 * @see ResponseMessage
 * @see ResponseFunctionCall
 */
@ExperimentalOpenRouterApi
@Serializable
public data class ResponseToolCall(
    @SerialName("id")
    val id: String,
    @SerialName("type")
    val type: String,
    @SerialName("function")
    val function: ResponseFunctionCall
)

/**
 * Details of a function call within a tool call.
 *
 * **Note:** This API is experimental and subject to change. It is marked with [ExperimentalOpenRouterApi].
 *
 * @property name Name of the function being called
 * @property arguments JSON-encoded string containing the function arguments
 *
 * @see ResponseToolCall
 */
@ExperimentalOpenRouterApi
@Serializable
public data class ResponseFunctionCall(
    @SerialName("name")
    val name: String,
    @SerialName("arguments")
    val arguments: String
)
